/**
 * ND500 Instruction Validation Test Runner
 *
 * Executes instruction tests from nd500-conformance.json and validates CPU state.
 * Tests are generated by the C# emulator for cross-validation.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <cjson/cJSON.h>
#include "conformance_corpus.h"
#include "../src/cpu/cpu_protos.h"
#include "../src/cpu/nd500_mmu.h"   /* For program/data space capability setup */
#include "../src/machine/machine_protos.h"

/*
 * Render a trap-condition mask as architecture names, e.g.
 *   0x0000000200 -> "O(9)"      0x0000000800 -> "IVO(11)"
 *   0x0000010000 -> "IOV(16)"   0x0000000004:32 -> "IOS(34)"
 *
 * A bare hex mask in a failure message is unreadable, and telling O from IVO
 * from IOV from IOS by eye is exactly the judgement these tests exist to make.
 * Returns a pointer to a rotating static buffer, so two calls can be used in
 * one printf (as the expected/actual pair below does).
 */
static const char* nd500_trap_bits_str(uint64_t bits) {
    static char bufs[2][256];
    static int which = 0;
    static const struct { uint64_t bit; const char* name; } tbl[] = {
        { 1ULL <<  9, "O(9)"     }, { 1ULL << 11, "IVO(11)" },
        { 1ULL << 12, "DZ(12)"   }, { 1ULL << 13, "FU(13)"  },
        { 1ULL << 14, "FO(14)"   }, { 1ULL << 15, "BO(15)"  },
        { 1ULL << 16, "IOV(16)"  }, { 1ULL << 17, "SIT(17)" },
        { 1ULL << 18, "BT(18)"   }, { 1ULL << 19, "CT(19)"  },
        { 1ULL << 20, "BPT(20)"  }, { 1ULL << 21, "ATF(21)" },
        { 1ULL << 22, "ATR(22)"  }, { 1ULL << 23, "ATW(23)" },
        { 1ULL << 24, "AZ(24)"   }, { 1ULL << 25, "DR(25)"  },
        { 1ULL << 26, "IX(26)"   }, { 1ULL << 27, "STO(27)" },
        { 1ULL << 28, "STU(28)"  }, { 1ULL << 29, "PRT(29)" },
        { 1ULL << 30, "DT(30)"   }, { 1ULL << 31, "DE(31)"  },
        { 1ULL << 32, "XSE(32)"  }, { 1ULL << 33, "IIC(33)" },
        { 1ULL << 34, "IOS(34)"  }, { 1ULL << 35, "ISE(35)" },
        { 1ULL << 36, "PV(36)"   }, { 1ULL << 37, "THM(37)" },
        { 1ULL << 38, "PGF(38)"  }, { 1ULL << 39, "PWF(39)" },
        { 1ULL << 40, "PRF(40)"  }, { 1ULL << 41, "HF(41)"  },
    };
    char* out = bufs[which];
    which ^= 1;
    out[0] = '\0';
    if (bits == 0) { snprintf(out, 256, "(none)"); return out; }
    size_t used = 0;
    for (size_t i = 0; i < sizeof tbl / sizeof tbl[0]; i++) {
        if (!(bits & tbl[i].bit)) continue;
        int n = snprintf(out + used, 256 - used, "%s%s", used ? "|" : "", tbl[i].name);
        if (n < 0 || (size_t)n >= 256 - used) break;
        used += (size_t)n;
        bits &= ~tbl[i].bit;
    }
    /* Anything left is a bit this table does not name - say so rather than
     * silently dropping it. */
    if (bits && used < 250)
        snprintf(out + used, 256 - used, "%s+0x%llX", used ? "|" : "",
                 (unsigned long long)bits);
    return out;
}

/* Test configuration */
#define MEMORY_SIZE (1 << 20)  /* 1MB */
#define MAX_FAILURE_DETAILS 500 /* Max failures to show in detail */

/* Track unknown elements globally for summary */
static int unknown_reg_count = 0;
static int unknown_field_count = 0;
static int unknown_initial_field_count = 0;
static int unknown_final_field_count = 0;

/* Strict mode validation statistics */
typedef struct {
    int pc_only_tests;           /* Tests validating only PC */
    int no_memory_validation;    /* Tests with empty final.ram */
    int minimal_validation;      /* Tests with <= 2 expected registers */
    int total_analyzed;          /* Total tests analyzed in strict mode */
} StrictValidationStats;

static StrictValidationStats strict_stats = {0};

/* Negative test statistics - tracks expected-to-fail tests */
typedef struct {
    int total_negative;          /* Total negative tests encountered */
    int correctly_failed;        /* Negative tests that failed as expected */
    int incorrectly_passed;      /* Negative tests that unexpectedly passed (BUG!) */
    int wrong_flags;             /* Negative tests with wrong_flag type */
    int wrong_registers;         /* Negative tests with wrong_register type */
    int wrong_memory;            /* Negative tests with wrong_memory type */
} NegativeTestStats;

static NegativeTestStats negative_stats = {0};

/**
 * Check if a top-level test field name is known
 */
static int is_known_test_field(const char* name) {
    static const char* known_fields[] = {
        "name", "assembly", "bytes", "initial", "final", "maxInstructions",
        "strictMemory", "requiresCallContext", "expectedTrap", "expectedTrapBits",
        /* Negative test fields - for tests that SHOULD fail validation */
        "isNegativeTest", "negativeTestType", "expectedValidationFailure",
        NULL
    };
    for (int i = 0; known_fields[i] != NULL; i++) {
        if (strcmp(name, known_fields[i]) == 0) return 1;
    }
    return 0;
}

/**
 * Check if an initial/final state field name is known
 */
static int is_known_state_field(const char* name) {
    static const char* known_fields[] = {
        "regs", "ram", "nd100_memory", "program_ram", NULL
    };
    for (int i = 0; known_fields[i] != NULL; i++) {
        if (strcmp(name, known_fields[i]) == 0) return 1;
    }
    return 0;
}

/**
 * Validate test structure and report unknown fields
 * Returns number of unknown fields found
 */
static int validate_test_structure(cJSON* test, const char* test_name, int print_warnings) {
    int unknown = 0;

    /* Check top-level fields */
    cJSON* field;
    cJSON_ArrayForEach(field, test) {
        if (field->string && !is_known_test_field(field->string)) {
            if (print_warnings) {
                printf("  WARNING: Unknown top-level field '%s' in test '%s'\n",
                       field->string, test_name);
            }
            unknown++;
            unknown_field_count++;
        }
    }

    /* Check initial state fields */
    cJSON* initial = cJSON_GetObjectItem(test, "initial");
    if (initial && cJSON_IsObject(initial)) {
        cJSON_ArrayForEach(field, initial) {
            if (field->string && !is_known_state_field(field->string)) {
                if (print_warnings) {
                    printf("  WARNING: Unknown field '%s' in initial state of test '%s'\n",
                           field->string, test_name);
                }
                unknown++;
                unknown_initial_field_count++;
            }
        }
    }

    /* Check final state fields */
    cJSON* final = cJSON_GetObjectItem(test, "final");
    if (final && cJSON_IsObject(final)) {
        cJSON_ArrayForEach(field, final) {
            if (field->string && !is_known_state_field(field->string)) {
                if (print_warnings) {
                    printf("  WARNING: Unknown field '%s' in final state of test '%s'\n",
                           field->string, test_name);
                }
                unknown++;
                unknown_final_field_count++;
            }
        }
    }

    return unknown;
}

/* Forward declarations */
static int run_single_test(Nd500Machine* m, cJSON* test, int test_num, int total, int verbose, int show_details);

/* ---------------------------------------------------------------------------
 * Quarantined corpus cases
 *
 * RetroCore generates this corpus; nd500x only runs it. When a case's EXPECTED
 * value is itself wrong, nd500x cannot fix it here - the fix has to happen in
 * the generator and the corpus be regenerated. Until then the case sits in this
 * table so one known-bad expectation does not mask every other regression.
 *
 * The rules this obeys, so it can never become a dumping ground:
 *   1. An entry needs a reason naming the SOURCE that overrules the corpus -
 *      the manual or the microcode, never "our emulator disagrees".
 *   2. The case is still executed and still printed, as QUARANTINED.
 *   3. If it starts passing, the run FAILS telling you to delete the entry.
 *      A stale quarantine is a bug too.
 *   4. It must be reported to the generator side. Both entries below are in
 *      docs/SPEC-CORPUS-SOLO-TUTTI-DT-DE.md and shared-file item 14.
 * ------------------------------------------------------------------------- */
static const struct { const char* name; const char* reason; }
conformance_quarantine[] = {
    /* EMPTY, and that is the goal state.
     *
     * It held four entries - tutti_Default, dcc_Default, pcc_Default and
     * ddirt_Default - all victims of ONE generator defect: a SYSTEM-class
     * catch-all in ComprehensiveSystemGenerator that expected every instruction
     * without a bespoke generator to raise IIC "because privileged instructions
     * do when executed in user mode". None of those four is privileged. The
     * manual marks privileged instructions explicitly (15.17 CLINIT, 16.13
     * DMON), and 16.2 TUTTI, 16.10 DCC, 16.11 DDIRT and 16.12 PCC each lack
     * that line - three of them say "Trap conditions: None" outright.
     *
     * FIXED at the source on 2026-08-17 (RetroCore ComprehensiveSystemGenerator,
     * an explicit unprivileged set) and the corpus regenerated, so the wrong
     * expectation is gone from the data rather than skipped in the runner.
     *
     * Leave the mechanism in place. It costs nothing while empty and it is the
     * right shape for the next corpus defect: quarantine the case WITH its
     * evidence, keep executing it, and fail the run when it starts passing so a
     * stale entry cannot rot here. Both of those behaviours are what turned this
     * table back into an empty one.
     */
    { NULL, NULL }
};

static const char* conformance_quarantine_reason(const char* name) {
    if (!name) return NULL;
    for (int i = 0; conformance_quarantine[i].name; i++)
        if (strcmp(name, conformance_quarantine[i].name) == 0)
            return conformance_quarantine[i].reason;
    return NULL;
}
static void set_register(Nd500Cpu* cpu, const char* name, uint32_t value);
static uint32_t get_register(Nd500Cpu* cpu, const char* name);
static int validate_registers(Nd500Cpu* cpu, cJSON* final_regs, int print_details);
static int validate_memory(Nd500Machine* m, cJSON* final_ram, int print_details);
static int validate_nd100_memory(Nd500Cpu* cpu, Nd500Machine* m, cJSON* final_nd100, int print_details);
static void analyze_test_coverage(cJSON* test, int verbose);

/**
 * Count number of expected registers in final state
 */
static int count_expected_registers(cJSON* test) {
    cJSON* final = cJSON_GetObjectItem(test, "final");
    if (!final) return 0;
    cJSON* final_regs = cJSON_GetObjectItem(final, "regs");
    if (!final_regs || !cJSON_IsObject(final_regs)) return 0;

    int count = 0;
    cJSON* reg;
    cJSON_ArrayForEach(reg, final_regs) {
        if (cJSON_IsNumber(reg)) count++;
    }
    return count;
}

/**
 * Check if test has memory validation
 */
static int has_memory_validation(cJSON* test) {
    cJSON* final = cJSON_GetObjectItem(test, "final");
    if (!final) return 0;
    cJSON* final_ram = cJSON_GetObjectItem(final, "ram");
    if (!final_ram || !cJSON_IsArray(final_ram)) return 0;
    return cJSON_GetArraySize(final_ram) > 0;
}

/**
 * Check if test only validates PC register
 */
static int is_pc_only_test(cJSON* test) {
    cJSON* final = cJSON_GetObjectItem(test, "final");
    if (!final) return 0;
    cJSON* final_regs = cJSON_GetObjectItem(final, "regs");
    if (!final_regs || !cJSON_IsObject(final_regs)) return 0;

    int count = 0;
    int has_pc = 0;
    cJSON* reg;
    cJSON_ArrayForEach(reg, final_regs) {
        if (cJSON_IsNumber(reg)) {
            count++;
            if (reg->string && strcmp(reg->string, "pc") == 0) {
                has_pc = 1;
            }
        }
    }
    return (count == 1 && has_pc);
}

/**
 * Analyze test for strict mode validation coverage
 */
static void analyze_test_coverage(cJSON* test, int verbose) {
    cJSON* name_json = cJSON_GetObjectItem(test, "name");
    const char* test_name = (name_json && cJSON_IsString(name_json))
        ? name_json->valuestring : "unnamed";

    strict_stats.total_analyzed++;

    int reg_count = count_expected_registers(test);
    int has_mem = has_memory_validation(test);
    int pc_only = is_pc_only_test(test);

    if (pc_only) {
        strict_stats.pc_only_tests++;
        if (verbose) {
            printf("  STRICT: %s - PC-only validation\n", test_name);
        }
    }

    if (reg_count <= 2 && !has_mem) {
        strict_stats.minimal_validation++;
        if (verbose && !pc_only) {
            printf("  STRICT: %s - minimal validation (%d regs, no memory)\n",
                   test_name, reg_count);
        }
    }

    /* Check for expected memory validation based on instruction type */
    cJSON* assembly = cJSON_GetObjectItem(test, "assembly");
    if (assembly && cJSON_IsString(assembly)) {
        const char* asm_str = assembly->valuestring;
        /* Instructions that typically write to memory */
        int should_have_memory = (
            strstr(asm_str, "LPUT") != NULL ||
            strstr(asm_str, "BMOVE") != NULL ||
            strstr(asm_str, "WPCONV") != NULL ||
            strstr(asm_str, "TSET") != NULL
        );
        if (should_have_memory && !has_mem) {
            strict_stats.no_memory_validation++;
            if (verbose) {
                printf("  STRICT: %s - expected memory validation for %s\n",
                       test_name, asm_str);
            }
        }
    }
}

/* Load JSON file into memory */
int main(int argc, char** argv) {
    const char* json_path = "nd500-conformance.json";
    int start_test = 0;
    int max_tests = -1;  /* -1 = run all */
    const char* filter = NULL;

    int continue_on_fail = 0;  /* --continue flag */
    int verbose = 0;           /* --verbose flag */
    int strict_mode = 0;       /* --strict flag */

    /* Parse command line arguments */
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--start") == 0 && i + 1 < argc) {
            start_test = atoi(argv[++i]);
        } else if (strcmp(argv[i], "--count") == 0 && i + 1 < argc) {
            max_tests = atoi(argv[++i]);
        } else if (strcmp(argv[i], "--filter") == 0 && i + 1 < argc) {
            filter = argv[++i];
        } else if (strcmp(argv[i], "--file") == 0 && i + 1 < argc) {
            json_path = argv[++i];
        } else if (strcmp(argv[i], "--continue") == 0) {
            continue_on_fail = 1;
        } else if (strcmp(argv[i], "--verbose") == 0 || strcmp(argv[i], "-v") == 0) {
            verbose = 1;
        } else if (strcmp(argv[i], "--strict") == 0) {
            strict_mode = 1;
        } else if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            printf("Usage: %s [options]\n", argv[0]);
            printf("Options:\n");
            printf("  --file <path>    JSON test file (default: nd500-conformance.json)\n");
            printf("  --start <n>      Start at test number n (0-indexed)\n");
            printf("  --count <n>      Run only n tests\n");
            printf("  --filter <str>   Only run tests with names containing str\n");
            printf("  --continue       Continue past failures (show summary at end)\n");
            printf("  --verbose, -v    Show all test results, not just failures\n");
            printf("  --strict         Analyze test validation coverage and report weak tests\n");
            printf("  --help           Show this help\n");
            return 0;
        }
    }

    printf("ND500 Instruction Validation Tests\n");
    printf("===================================\n\n");

    cJSON* root = conformance_corpus_load(argv[0], json_path);
    if (!root) {
        return 1;
    }

    int total_tests = cJSON_GetArraySize(root);
    printf("Found %d test cases\n\n", total_tests);

    /* Initialize machine and CPU */
    Nd500Machine machine;
    Nd500Cpu cpu;
    memset(&machine, 0, sizeof(machine));
    memset(&cpu, 0, sizeof(cpu));
    nd500_machine_init(&machine, MEMORY_SIZE);
    nd500_cpu_init(&cpu, &machine);

    /* Run tests */
    int passed = 0;
    int failed = 0;
    int skipped = 0;
    int quarantined = 0;
    int quarantine_stale = 0;
    int test_num = 0;
    int failures_shown = 0;

    /* Failure tracking for summary */
    typedef struct {
        char name[128];
        char assembly[256];
    } FailedTest;
    FailedTest* failed_tests = NULL;
    int failed_capacity = 0;

    if (continue_on_fail) {
        failed_capacity = 1000;
        failed_tests = (FailedTest*)calloc(failed_capacity, sizeof(FailedTest));
    }

    cJSON* test;
    cJSON_ArrayForEach(test, root) {
        /* Skip tests before start_test */
        if (test_num < start_test) {
            test_num++;
            skipped++;
            continue;
        }

        /* Check max_tests limit */
        if (max_tests >= 0 && (passed + failed) >= max_tests) {
            break;
        }

        /* Check filter */
        cJSON* name = cJSON_GetObjectItem(test, "name");
        if (filter && name && cJSON_IsString(name)) {
            if (strstr(name->valuestring, filter) == NULL) {
                test_num++;
                skipped++;
                continue;
            }
        }

        /* Strict mode: analyze test coverage before running */
        if (strict_mode) {
            analyze_test_coverage(test, verbose);
        }

        /* Determine if we should show details for this test */
        int show_details = continue_on_fail ? (failures_shown < MAX_FAILURE_DETAILS) : 1;
        int result = run_single_test(&machine, test, test_num + 1, total_tests, verbose, show_details);

        /* Quarantine: a case whose EXPECTATION is wrong, reported to the
         * generator side and not yet regenerated. See conformance_quarantine[]
         * for the rule this obeys - it never hides a case, and it fails the run
         * if the case starts passing so the entry cannot go stale. */
        {
            cJSON* qn = cJSON_GetObjectItem(test, "name");
            const char* qname = (qn && cJSON_IsString(qn)) ? qn->valuestring : "";
            const char* why = conformance_quarantine_reason(qname);
            if (why) {
                if (result != 0) {
                    printf("Test %d/%d: %s ... QUARANTINED (corpus expectation is wrong: %s)\n",
                           test_num + 1, total_tests, qname, why);
                    quarantined++;
                    continue;
                }
                printf("Test %d/%d: %s ... QUARANTINE IS STALE - the case now passes, "
                       "delete its entry in conformance_quarantine[]\n",
                       test_num + 1, total_tests, qname);
                quarantine_stale++;
            }
        }

        if (result == 0) {
            passed++;
        } else {
            failed++;
            if (show_details) failures_shown++;

            /* Track failed test for summary */
            if (failed_tests && failed < failed_capacity) {
                cJSON* asm_json = cJSON_GetObjectItem(test, "assembly");
                strncpy(failed_tests[failed-1].name,
                        name && cJSON_IsString(name) ? name->valuestring : "unnamed",
                        sizeof(failed_tests[failed-1].name) - 1);
                strncpy(failed_tests[failed-1].assembly,
                        asm_json && cJSON_IsString(asm_json) ? asm_json->valuestring : "",
                        sizeof(failed_tests[failed-1].assembly) - 1);
            }

            if (!continue_on_fail) {
                /* Stop on first failure */
                printf("\nStopping on first failure. Use --continue to run all tests.\n");
                break;
            }
        }

        test_num++;
    }

    /* Print summary */
    printf("\n===================================\n");
    printf("Results: %d passed, %d failed, %d skipped (%.1f%% pass rate)\n",
           passed, failed, skipped,
           (passed + failed) > 0 ? (100.0 * passed / (passed + failed)) : 0);

    /* Quarantined cases are NOT counted as passes. Print them every run so a
     * known-bad expectation stays visible instead of quietly becoming normal. */
    if (quarantined > 0 || quarantine_stale > 0) {
        printf("\nQuarantined corpus cases: %d (expectation wrong, awaiting a "
               "regenerated corpus - see conformance_quarantine[])\n", quarantined);
        for (int i = 0; conformance_quarantine[i].name; i++)
            printf("  - %s\n", conformance_quarantine[i].name);
        if (quarantine_stale > 0)
            printf("  %d STALE entr%s - the case passes now; delete it from "
                   "conformance_quarantine[]\n",
                   quarantine_stale, quarantine_stale == 1 ? "y" : "ies");
    }

    /* Report any unknown JSON elements */
    int total_unknown = unknown_reg_count + unknown_field_count +
                        unknown_initial_field_count + unknown_final_field_count;
    if (total_unknown > 0) {
        printf("\nWARNING: Unknown JSON elements detected - test runner may need updates!\n");
        if (unknown_field_count > 0)
            printf("  - %d unknown top-level fields\n", unknown_field_count);
        if (unknown_initial_field_count > 0)
            printf("  - %d unknown fields in initial state\n", unknown_initial_field_count);
        if (unknown_final_field_count > 0)
            printf("  - %d unknown fields in final state\n", unknown_final_field_count);
        if (unknown_reg_count > 0)
            printf("  - %d unknown register names\n", unknown_reg_count);
        printf("Run with --verbose to see details.\n");
    }

    /* Strict mode validation coverage report */
    if (strict_mode && strict_stats.total_analyzed > 0) {
        printf("\n=== Validation Coverage Report (Strict Mode) ===\n");
        printf("Tests analyzed: %d\n", strict_stats.total_analyzed);
        printf("PC-only tests: %d (%.1f%%)\n",
               strict_stats.pc_only_tests,
               100.0 * strict_stats.pc_only_tests / strict_stats.total_analyzed);
        printf("Minimal validation (<=2 regs, no memory): %d (%.1f%%)\n",
               strict_stats.minimal_validation,
               100.0 * strict_stats.minimal_validation / strict_stats.total_analyzed);
        printf("Missing memory validation: %d\n", strict_stats.no_memory_validation);

        int strong_validation = strict_stats.total_analyzed - strict_stats.minimal_validation;
        printf("Strong validation: %d (%.1f%%)\n",
               strong_validation,
               100.0 * strong_validation / strict_stats.total_analyzed);

        if (strict_stats.pc_only_tests > 0 || strict_stats.no_memory_validation > 0) {
            printf("\nWARNING: Some tests have weak validation and may produce false positives.\n");
            printf("Use --verbose to see details of weak tests.\n");
        }
    }

    /* Negative test statistics report */
    if (negative_stats.total_negative > 0) {
        printf("\n=== Negative Test Report ===\n");
        printf("Negative tests (expected to fail): %d\n", negative_stats.total_negative);
        printf("  Correctly failed (GOOD): %d (%.1f%%)\n",
               negative_stats.correctly_failed,
               100.0 * negative_stats.correctly_failed / negative_stats.total_negative);
        printf("  Unexpectedly passed (BUG!): %d\n", negative_stats.incorrectly_passed);

        if (negative_stats.wrong_flags > 0 || negative_stats.wrong_registers > 0 ||
            negative_stats.wrong_memory > 0) {
            printf("By type:\n");
            if (negative_stats.wrong_flags > 0)
                printf("  - wrong_flag: %d\n", negative_stats.wrong_flags);
            if (negative_stats.wrong_registers > 0)
                printf("  - wrong_register: %d\n", negative_stats.wrong_registers);
            if (negative_stats.wrong_memory > 0)
                printf("  - wrong_memory: %d\n", negative_stats.wrong_memory);
        }

        if (negative_stats.incorrectly_passed > 0) {
            printf("\nCRITICAL: %d negative tests passed when they should have failed!\n",
                   negative_stats.incorrectly_passed);
            printf("This indicates bugs in the test framework validation logic.\n");
        } else {
            printf("\nAll negative tests correctly detected validation failures.\n");
        }
    }

    if (failed == 0 && passed > 0) {
        printf("\nALL TESTS PASSED\n");
    } else if (continue_on_fail && failed > 0) {
        /* Show failure summary with instruction patterns */
        printf("\nFailure Summary (first %d unique failures):\n", failed < 100 ? failed : 100);
        printf("-------------------------------------------\n");

        /* Count failures by instruction type */
        typedef struct { char prefix[32]; int count; } InstrCount;
        InstrCount instr_counts[100];
        int instr_count_num = 0;

        for (int i = 0; i < failed && i < failed_capacity; i++) {
            /* Extract instruction name from assembly (first word) */
            char instr[32] = {0};
            const char* asm_str = failed_tests[i].assembly;
            int j = 0;
            while (asm_str[j] && asm_str[j] != ' ' && j < 31) {
                instr[j] = asm_str[j];
                j++;
            }
            instr[j] = '\0';

            /* Find or add to counts */
            int found = 0;
            for (int k = 0; k < instr_count_num; k++) {
                if (strcmp(instr_counts[k].prefix, instr) == 0) {
                    instr_counts[k].count++;
                    found = 1;
                    break;
                }
            }
            if (!found && instr_count_num < 100) {
                strncpy(instr_counts[instr_count_num].prefix, instr, 31);
                instr_counts[instr_count_num].count = 1;
                instr_count_num++;
            }
        }

        /* Sort by count (descending) */
        for (int i = 0; i < instr_count_num - 1; i++) {
            for (int j = i + 1; j < instr_count_num; j++) {
                if (instr_counts[j].count > instr_counts[i].count) {
                    InstrCount tmp = instr_counts[i];
                    instr_counts[i] = instr_counts[j];
                    instr_counts[j] = tmp;
                }
            }
        }

        /* Print instruction failure counts */
        printf("Failures by instruction:\n");
        for (int i = 0; i < instr_count_num && i < 30; i++) {
            printf("  %-20s: %d failures\n", instr_counts[i].prefix, instr_counts[i].count);
        }
        if (instr_count_num > 30) {
            printf("  ... and %d more instruction types\n", instr_count_num - 30);
        }
    }

    /* Cleanup */
    if (failed_tests) free(failed_tests);
    nd500_machine_free(&machine);
    cJSON_Delete(root);

    return (failed > 0 || quarantine_stale > 0) ? 1 : 0;
}

/**
 * Run a single test case
 * Returns 0 on success, non-zero on failure
 * verbose: if true, print PASS for every test
 * show_details: if true, print failure details
 */
static int run_single_test(Nd500Machine* m, cJSON* test, int test_num, int total, int verbose, int show_details) {
    Nd500Cpu* cpu = m->cpu;

    /* Get test name */
    cJSON* name_json = cJSON_GetObjectItem(test, "name");
    const char* test_name = name_json && cJSON_IsString(name_json)
        ? name_json->valuestring : "unnamed";

    /* Validate test structure for unknown fields */
    validate_test_structure(test, test_name, show_details);

    /* Reset CPU and clear memory */
    nd500_cpu_reset(cpu);
    memset(m->memory, 0, m->memory_size);

    /* The raised-trap record is a FILE-SCOPE GLOBAL in cpu.c, not part of
     * Nd500Cpu, so nd500_cpu_reset() above cannot clear it. It was only ever
     * cleared inside the "if (nd500_trap_occurred())" branch further down, so
     * any test that returned before reaching that branch left its trap set and
     * the NEXT test was reported as trapping when it had not.
     *
     * Clear it up front so every test starts clean regardless of how the
     * previous one ended. */
    nd500_trap_clear();

    /* The MACHINE's run state is not part of Nd500Cpu either, so it also
     * survives nd500_cpu_reset(). A test whose instruction legitimately halts
     * the machine - Bp_Breakpoint raises IIC and leaves
     * "[STOP] illegal instruction at PC=0x1000 data=0x2", run_flag = 0 - left
     * the NEXT test running against a stopped machine, which surfaced as an
     * "unexpected trap: Unknown".
     *
     * That is exactly what made Noop_Default fail: it passes on its own
     * (--filter Noop is 2/2) and only fails in a full run, immediately after
     * the BP test. Put the machine back in a runnable state per test. */
    m->run_flag = 1;
    m->stop_reason = 0;
    m->stop_addr = 0;
    m->stop_data = 0;

    /* Get test components */
    cJSON* bytes = cJSON_GetObjectItem(test, "bytes");
    cJSON* initial = cJSON_GetObjectItem(test, "initial");
    cJSON* final = cJSON_GetObjectItem(test, "final");
    cJSON* max_instr = cJSON_GetObjectItem(test, "maxInstructions");

    if (!bytes || !initial || !final) {
        printf("Test %d/%d: %s ... SKIP (missing fields)\n", test_num, total, test_name);
        return 0;  /* Skip, don't fail */
    }

    cJSON* initial_regs = cJSON_GetObjectItem(initial, "regs");
    cJSON* initial_ram = cJSON_GetObjectItem(initial, "ram");
    cJSON* final_regs = cJSON_GetObjectItem(final, "regs");
    cJSON* final_ram = cJSON_GetObjectItem(final, "ram");
    cJSON* final_nd100 = cJSON_GetObjectItem(final, "nd100_memory");

    /* Get PC from initial regs (default 0x1000) */
    uint32_t pc_addr = 0x1000;
    if (initial_regs) {
        cJSON* pc_json = cJSON_GetObjectItem(initial_regs, "pc");
        if (pc_json && cJSON_IsNumber(pc_json)) {
            pc_addr = (uint32_t)pc_json->valuedouble;
        }
    }

    /* 1. Load instruction bytes at PC address */
    if (cJSON_IsArray(bytes)) {
        int byte_idx = 0;
        cJSON* byte_val;
        cJSON_ArrayForEach(byte_val, bytes) {
            if (cJSON_IsNumber(byte_val)) {
                nd500_bus_write8(m, pc_addr + byte_idx, (uint8_t)byte_val->valueint);
                byte_idx++;
            }
        }
    }

    /* 2. Set initial registers */
    if (initial_regs) {
        cJSON* reg;
        cJSON_ArrayForEach(reg, initial_regs) {
            if (cJSON_IsNumber(reg)) {
                set_register(cpu, reg->string, (uint32_t)reg->valuedouble);
            }
        }
    }

    /* 3. Set initial memory (byte or 32-bit word based on value size) */
    if (initial_ram && cJSON_IsArray(initial_ram)) {
        cJSON* mem_entry;
        cJSON_ArrayForEach(mem_entry, initial_ram) {
            if (cJSON_IsArray(mem_entry) && cJSON_GetArraySize(mem_entry) >= 2) {
                cJSON* addr_json = cJSON_GetArrayItem(mem_entry, 0);
                cJSON* val_json = cJSON_GetArrayItem(mem_entry, 1);
                if (cJSON_IsNumber(addr_json) && cJSON_IsNumber(val_json)) {
                    uint32_t addr = (uint32_t)addr_json->valuedouble;
                    uint32_t val = (uint32_t)val_json->valuedouble;
                    if (val <= 255) {
                        /* Single byte value */
                        nd500_bus_write8(m, addr, (uint8_t)val);
                    } else {
                        /* Write 32-bit value in big-endian (ND-500 byte order) */
                        nd500_bus_write8(m, addr + 0, (uint8_t)((val >> 24) & 0xFF));
                        nd500_bus_write8(m, addr + 1, (uint8_t)((val >> 16) & 0xFF));
                        nd500_bus_write8(m, addr + 2, (uint8_t)((val >> 8) & 0xFF));
                        nd500_bus_write8(m, addr + 3, (uint8_t)(val & 0xFF));
                    }
                }
            }
        }
    }

    /* 3b. Set ND-100 memory for I/O instruction testing (RIOM) */
    cJSON* nd100_mem = cJSON_GetObjectItem(initial, "nd100_memory");
    if (nd100_mem && cJSON_IsArray(nd100_mem)) {
        cJSON* mem_entry;
        cJSON_ArrayForEach(mem_entry, nd100_mem) {
            if (cJSON_IsArray(mem_entry) && cJSON_GetArraySize(mem_entry) >= 2) {
                cJSON* addr_json = cJSON_GetArrayItem(mem_entry, 0);
                cJSON* val_json = cJSON_GetArrayItem(mem_entry, 1);
                if (cJSON_IsNumber(addr_json) && cJSON_IsNumber(val_json)) {
                    uint32_t nd100_addr = (uint32_t)addr_json->valuedouble;
                    uint16_t halfword = (uint16_t)val_json->valuedouble;

                    /* Write to physical memory at ND-100 offset */
                    /* Physical address = nd100_memory_offset + (nd100_addr * 2) */
                    uint32_t phys_addr = cpu->nd100_memory_offset + (nd100_addr * 2);
                    nd500_bus_write8(m, phys_addr, (uint8_t)(halfword >> 8));
                    nd500_bus_write8(m, phys_addr + 1, (uint8_t)(halfword & 0xFF));
                }
            }
        }
    }

    /* 3d. Set PROGRAM SPACE memory (separate from data space)
     * This is for testing instructions like CALL/CALLG that must read from
     * program space (PMON) instead of data space (DMON).
     *
     * When program_ram is specified, we configure separate MMU mappings:
     * - Program capabilities point to program physical region (0x80000+)
     * - Data capabilities point to data physical region (0x00000+)
     * This allows same virtual address to return different values depending
     * on whether it's a program fetch or data read.
     *
     * Reference: ND-500 Reference Manual, Chapter 2 (Memory Architecture)
     */
    cJSON* initial_program_ram = cJSON_GetObjectItem(initial, "program_ram");
    if (initial_program_ram && cJSON_IsArray(initial_program_ram) &&
        cJSON_GetArraySize(initial_program_ram) > 0) {

        /* Physical memory offset for program space (separate from data space) */
        const uint32_t PROG_PHYS_OFFSET = 0x80000;

        /* Initialize MMU tables first (required before enabling) */
        nd500_mmu_init(cpu);

        /* Enable MMU (both program and data) */
        nd500_mmu_enable(cpu);  /* Enables both program and data MMU */

        /* For each address in program_ram, configure capabilities
         * so program space maps to PROG_PHYS_OFFSET region
         * and data space maps to 0x0 region (normal ram locations).
         *
         * We use domain 0, and set up minimal capability that maps
         * the segment containing the address.
         */
        cJSON* mem_entry;
        cJSON_ArrayForEach(mem_entry, initial_program_ram) {
            if (cJSON_IsArray(mem_entry) && cJSON_GetArraySize(mem_entry) >= 2) {
                cJSON* addr_json = cJSON_GetArrayItem(mem_entry, 0);
                cJSON* val_json = cJSON_GetArrayItem(mem_entry, 1);
                if (cJSON_IsNumber(addr_json) && cJSON_IsNumber(val_json)) {
                    uint32_t vaddr = (uint32_t)addr_json->valuedouble;
                    uint32_t val = (uint32_t)val_json->valuedouble;

                    /* Extract segment from virtual address */
                    uint8_t segment = (vaddr >> 27) & 0x1F;

                    /* Configure program capability: PSN pointing to program phys region */
                    /* Use PSN value that maps to PROG_PHYS_OFFSET */
                    uint16_t prog_psn = (PROG_PHYS_OFFSET >> 11) & 0xFFFF;  /* PSN = page frame */
                    nd500_mmu_set_program_capability(cpu, 0, segment, prog_psn);

                    /* Configure data capability: PSN pointing to regular memory */
                    uint16_t data_psn = 0;  /* Maps to physical 0 */
                    nd500_mmu_set_data_capability(cpu, 0, segment, data_psn);

                    /* Also set up segment 0 (where PC typically starts) if different */
                    uint8_t pc_segment = (pc_addr >> 27) & 0x1F;
                    if (pc_segment != segment) {
                        nd500_mmu_set_program_capability(cpu, 0, pc_segment, 0);
                        nd500_mmu_set_data_capability(cpu, 0, pc_segment, 0);
                    }

                    /* Write value to PROGRAM space physical memory */
                    uint32_t prog_phys_addr = PROG_PHYS_OFFSET + (vaddr & 0x7FFFFFF);
                    if (val <= 255) {
                        nd500_bus_write8(m, prog_phys_addr, (uint8_t)val);
                    } else {
                        /* Write 32-bit in big-endian */
                        nd500_bus_write8(m, prog_phys_addr + 0, (uint8_t)((val >> 24) & 0xFF));
                        nd500_bus_write8(m, prog_phys_addr + 1, (uint8_t)((val >> 16) & 0xFF));
                        nd500_bus_write8(m, prog_phys_addr + 2, (uint8_t)((val >> 8) & 0xFF));
                        nd500_bus_write8(m, prog_phys_addr + 3, (uint8_t)(val & 0xFF));
                    }
                }
            }
        }

        /* Set current domain to 0 (where we configured capabilities) */
        cpu->CED = 0;
        cpu->CAD = 0;
    }

    /* 3c. Check for requiresCallContext flag - set up pending CALL context for ENT* tests */
    cJSON* requires_call = cJSON_GetObjectItem(test, "requiresCallContext");
    if (requires_call && cJSON_IsTrue(requires_call)) {
        /* ENT* instructions require a preceding CALL to have set up context.
         * We simulate this by setting up the pending call return address.
         * Use a typical return address value (0x5000 as in the generator).
         */
        cpu->pending_call_return_address = 0x5000;
        cpu->pending_call_arg_count = 0;
    }

    /* 4. Get expected trap (if any) */
    /* Exact condition mask, when the case pins one. Bits run 0..41, so the
     * value always fits a double exactly (2^41 < 2^53) and a plain JSON number
     * is lossless here. -1 means "not specified". */
    cJSON* expected_bits_json = cJSON_GetObjectItem(test, "expectedTrapBits");
    int have_expected_bits = 0;
    uint64_t expected_trap_bits = 0;
    if (expected_bits_json && cJSON_IsNumber(expected_bits_json)) {
        expected_trap_bits = (uint64_t)expected_bits_json->valuedouble;
        have_expected_bits = 1;
    }

    cJSON* expected_trap_json = cJSON_GetObjectItem(test, "expectedTrap");
    const char* expected_trap = NULL;
    if (expected_trap_json && cJSON_IsString(expected_trap_json)) {
        expected_trap = expected_trap_json->valuestring;
    }

    /* 5. Execute instruction(s) */
    int instructions = 1;
    if (max_instr && cJSON_IsNumber(max_instr)) {
        instructions = max_instr->valueint;
    }

    int trap_occurred = 0;
    char actual_trap_type[64] = {0};  /* Copy trap name before clearing state */
    char actual_trap_desc[256] = {0};
    uint32_t trap_pc = 0;
    /* The EXACT condition bit(s) raised, not the lossy name. "expectedTrap" is
     * a 5-token enum (DivisionByZero, FloatException, IllegalInstruction,
     * IllegalOperandValue, InstructionSequenceError) shared with the C# side,
     * and it collapses conditions the ND-500 keeps apart: FloatException covers
     * IVO+FU+FO, IllegalOperandValue covers BOTH IOV(16) and IOS(34), and there
     * is no token at all for O(9), integer overflow. That is precisely why 19
     * wrong trap numbers survived this corpus. "expectedTrapBits" carries the
     * raw 64-bit mask so a case can pin the exact bit. */
    uint64_t actual_trap_bits = 0;

    /* Save initial ST1 to detect newly-set trap flags */
    uint32_t initial_st1 = cpu->ST1;

    for (int i = 0; i < instructions; i++) {
        nd500_cpu_step(cpu);

        /* Check for traps - first check global trap state (interrupt-class traps) */
        if (nd500_trap_occurred()) {
            const Nd500TrapState* trap = nd500_trap_get_state();
            trap_occurred = 1;
            /* Copy strings before clearing - trap_clear zeros the global state */
            strncpy(actual_trap_type, trap->trap_name, sizeof(actual_trap_type) - 1);
            strncpy(actual_trap_desc, trap->trap_description, sizeof(actual_trap_desc) - 1);
            trap_pc = trap->trap_pc;
            actual_trap_bits = trap->trap_condition;
            nd500_trap_clear();
            break;  /* Stop on trap */
        }

        /* Also check for ignorable traps via ST1 flags.
         *
         * An ignorable trap that is NOT enabled in OTE never reaches
         * nd500_trap_set_state(), so the global trap state stays empty and this
         * status-bit scan is the only way to observe it.
         *
         * This used to be a copy-pasted if-ladder over five bits (DZ, IOV, FO,
         * FU, BO) that recorded only a name. It had no branch for O(9) at all,
         * so integer overflow - the condition fifteen wrong-trap sites turned
         * on - was invisible here. Table-driven now, covering every ignorable
         * condition it can name, and it records the exact bits as well as the
         * name so expectedTrapBits can be asserted.
         *
         * Names are unchanged from the ladder (the same vocabulary the C#
         * TrapType uses), so existing expectations still match; the bits are
         * the new, precise channel. Order matters only in that the first
         * newly-set bit wins, matching the old ladder's behaviour. */
        if (expected_trap != NULL) {
            static const struct { uint32_t bit; const char* name; } ignorable[] = {
                { 1u << 12, "DivisionByZero"      },  /* DZ  */
                { 1u << 16, "IllegalOperandValue" },  /* IOV */
                { 1u << 14, "FloatException"      },  /* FO  */
                { 1u << 13, "FloatException"      },  /* FU  */
                { 1u << 11, "FloatException"      },  /* IVO */
                { 1u << 15, "Overflow"            },  /* BO  */
                { 1u <<  9, "IntegerOverflow"     },  /* O   */
                { 1u << 27, "StackOverflow"       },  /* STO */
                { 1u << 28, "StackUnderflow"      },  /* STU */
                { 1u << 25, "AddressingError"     },  /* DR: ignorable (manual 6.5.3) */
                { 1u << 26, "AddressingError"     },  /* IX: ignorable (manual 6.5.3) */
            };
            uint32_t new_flags = cpu->ST1 & ~initial_st1;
            for (size_t t = 0; t < sizeof ignorable / sizeof ignorable[0]; t++) {
                if (!(new_flags & ignorable[t].bit)) continue;
                trap_occurred = 1;
                strncpy(actual_trap_type, ignorable[t].name, sizeof(actual_trap_type) - 1);
                actual_trap_bits = (uint64_t)ignorable[t].bit;
                trap_pc = cpu->PC;
                break;
            }
            if (trap_occurred) break;
        }
    }

    /* 6. Validate trap expectations */
    if (expected_trap != NULL) {
        /* Test expects a trap */
        if (!trap_occurred) {
            if (show_details) {
                printf("Test %d/%d: %s ... FAIL (expected trap)\n", test_num, total, test_name);
                cJSON* assembly = cJSON_GetObjectItem(test, "assembly");
                if (assembly && cJSON_IsString(assembly)) {
                    printf("  Assembly: %s\n", assembly->valuestring);
                }
                printf("  Expected trap: %s, but no trap occurred\n", expected_trap);
            }
            return 1;
        }

        /* Trap occurred - check if type matches */
        if (actual_trap_type[0] == '\0' || strcmp(actual_trap_type, expected_trap) != 0) {
            if (show_details) {
                printf("Test %d/%d: %s ... FAIL (wrong trap type)\n", test_num, total, test_name);
                cJSON* assembly = cJSON_GetObjectItem(test, "assembly");
                if (assembly && cJSON_IsString(assembly)) {
                    printf("  Assembly: %s\n", assembly->valuestring);
                }
                printf("  Expected trap: %s\n", expected_trap);
                printf("  Actual trap: %s (%s) at PC=0x%08X\n",
                       actual_trap_type[0] ? actual_trap_type : "unknown",
                       actual_trap_desc[0] ? actual_trap_desc : "", trap_pc);
            }
            return 1;
        }

        /* The name matched, but the name is coarse. If the case pins the exact
         * condition, that is the assertion that actually distinguishes O(9)
         * from IVO(11) from IOV(16) from IOS(34) - the differences every one of
         * the 19 wrong-trap bugs lived in, and which the name alone cannot
         * see. */
        if (have_expected_bits && actual_trap_bits != expected_trap_bits) {
            if (show_details) {
                printf("Test %d/%d: %s ... FAIL (wrong trap BITS)\n", test_num, total, test_name);
                cJSON* assembly = cJSON_GetObjectItem(test, "assembly");
                if (assembly && cJSON_IsString(assembly)) {
                    printf("  Assembly: %s\n", assembly->valuestring);
                }
                printf("  Trap name matched (%s), but the condition differs:\n", expected_trap);
                printf("    expected bits 0x%016llX  %s\n",
                       (unsigned long long)expected_trap_bits,
                       nd500_trap_bits_str(expected_trap_bits));
                printf("    actual   bits 0x%016llX  %s\n",
                       (unsigned long long)actual_trap_bits,
                       nd500_trap_bits_str(actual_trap_bits));
            }
            return 1;
        }

        /* Trap matched - test passes (skip register/memory validation for trap tests) */
        if (verbose) {
            printf("Test %d/%d: %s ... PASS (trap: %s)\n", test_num, total, test_name, expected_trap);
        }
        return 0;
    } else {
        /* Test does NOT expect a trap */
        if (trap_occurred) {
            if (show_details) {
                printf("Test %d/%d: %s ... FAIL (unexpected trap)\n", test_num, total, test_name);
                cJSON* assembly = cJSON_GetObjectItem(test, "assembly");
                if (assembly && cJSON_IsString(assembly)) {
                    printf("  Assembly: %s\n", assembly->valuestring);
                }
                printf("  Trap: %s (%s) at PC=0x%08X\n",
                       actual_trap_type[0] ? actual_trap_type : "unknown",
                       actual_trap_desc[0] ? actual_trap_desc : "", trap_pc);
            }
            return 1;
        }
    }

    /* 7. Validate final registers (without printing details yet) */
    int reg_result = 0;
    if (final_regs) {
        reg_result = validate_registers(cpu, final_regs, 0);
    }

    /* 8. Validate final memory (without printing details yet) */
    int mem_result = 0;
    if (final_ram && cJSON_IsArray(final_ram) && cJSON_GetArraySize(final_ram) > 0) {
        mem_result = validate_memory(m, final_ram, 0);
    }

    /* 9. Validate final ND-100 memory (I/O processor memory) */
    int nd100_result = 0;
    if (final_nd100 && cJSON_IsArray(final_nd100) && cJSON_GetArraySize(final_nd100) > 0) {
        nd100_result = validate_nd100_memory(cpu, m, final_nd100, 0);
    }

    /* 10. Check if this is a negative test (expected to fail) */
    cJSON* is_negative = cJSON_GetObjectItem(test, "isNegativeTest");
    int negative_test = is_negative && cJSON_IsTrue(is_negative);

    if (negative_test) {
        /* Track negative test type for statistics */
        cJSON* neg_type = cJSON_GetObjectItem(test, "negativeTestType");
        if (neg_type && cJSON_IsString(neg_type)) {
            if (strcmp(neg_type->valuestring, "wrong_flag") == 0)
                negative_stats.wrong_flags++;
            else if (strcmp(neg_type->valuestring, "wrong_register") == 0)
                negative_stats.wrong_registers++;
            else if (strcmp(neg_type->valuestring, "wrong_memory") == 0)
                negative_stats.wrong_memory++;
        }

        negative_stats.total_negative++;

        /* For negative tests, validation FAILURE is the expected outcome */
        int validation_failed = (reg_result != 0 || mem_result != 0 || nd100_result != 0);

        if (validation_failed) {
            /* PASS: Negative test correctly failed validation */
            negative_stats.correctly_failed++;
            if (verbose) {
                cJSON* expected_fail = cJSON_GetObjectItem(test, "expectedValidationFailure");
                printf("Test %d/%d: %s ... PASS (negative test correctly failed", test_num, total, test_name);
                if (expected_fail && cJSON_IsString(expected_fail)) {
                    printf(" on %s", expected_fail->valuestring);
                }
                printf(")\n");
            }
            return 0;  /* Pass */
        } else {
            /* FAIL: Negative test unexpectedly passed - indicates bug in test framework! */
            negative_stats.incorrectly_passed++;
            if (show_details) {
                printf("Test %d/%d: %s ... FAIL (NEGATIVE TEST PASSED UNEXPECTEDLY!)\n",
                       test_num, total, test_name);

                /* Show assembly source */
                cJSON* assembly = cJSON_GetObjectItem(test, "assembly");
                if (assembly && cJSON_IsString(assembly)) {
                    printf("  Assembly: %s\n", assembly->valuestring);
                }

                printf("  This indicates a BUG in the test framework!\n");
                printf("  The test had intentionally wrong expected values but validation passed.\n");

                cJSON* neg_type_dbg = cJSON_GetObjectItem(test, "negativeTestType");
                cJSON* expected_fail_dbg = cJSON_GetObjectItem(test, "expectedValidationFailure");
                if (neg_type_dbg && cJSON_IsString(neg_type_dbg)) {
                    printf("  Negative test type: %s\n", neg_type_dbg->valuestring);
                }
                if (expected_fail_dbg && cJSON_IsString(expected_fail_dbg)) {
                    printf("  Expected validation failure on: %s\n", expected_fail_dbg->valuestring);
                }
            }
            return 1;  /* Fail */
        }
    }

    /* Normal (positive) test - validation should pass */
    if (reg_result != 0 || mem_result != 0 || nd100_result != 0) {
        if (show_details) {
            printf("Test %d/%d: %s ... FAIL\n", test_num, total, test_name);

            /* Show assembly source */
            cJSON* assembly = cJSON_GetObjectItem(test, "assembly");
            if (assembly && cJSON_IsString(assembly)) {
                printf("  Assembly: %s\n", assembly->valuestring);
            }

            /* Show instruction bytes */
            printf("  Bytes at 0x%08X: ", pc_addr);
            if (cJSON_IsArray(bytes)) {
                cJSON* b;
                cJSON_ArrayForEach(b, bytes) {
                    if (cJSON_IsNumber(b)) {
                        printf("%02X ", b->valueint);
                    }
                }
            }
            printf("\n");

            /* Show initial state */
            printf("  Initial: ");
            if (initial_regs) {
                cJSON* r;
                cJSON_ArrayForEach(r, initial_regs) {
                    if (cJSON_IsNumber(r)) {
                        printf("%s=0x%X ", r->string, (uint32_t)(r->valuedouble));
                    }
                }
            }
            printf("\n");

            /* Show expected vs actual */
            printf("  Expected vs Actual:\n");
            if (final_regs) validate_registers(cpu, final_regs, 1);
            if (final_ram && cJSON_IsArray(final_ram)) validate_memory(m, final_ram, 1);
            if (final_nd100 && cJSON_IsArray(final_nd100)) validate_nd100_memory(cpu, m, final_nd100, 1);

            /* Show actual final state for debugging */
            printf("  Actual final state: PC=0x%08X I1=0x%08X ST1=0x%08X\n",
                   cpu->PC, cpu->I[0], cpu->ST1);
        }

        return 1;
    }

    if (verbose) {
        printf("Test %d/%d: %s ... PASS\n", test_num, total, test_name);
    }
    return 0;
}

/**
 * Set a CPU register by name
 */
static void set_register(Nd500Cpu* cpu, const char* name, uint32_t value) {
    if (strcmp(name, "pc") == 0) cpu->PC = value;
    else if (strcmp(name, "st") == 0) cpu->ST1 = value;
    /* ST2 holds trap condition bits 32..41 - XSE(32), IIC(33), IOS(34),
     * ISE(35), PV(36), THM(37), PGF(38), PWF(39), PRF(40), HF(41). The corpus
     * carried only "st" (= ST1), so none of those were ever asserted, which is
     * why the IOS-vs-ISE guard divergence between the two emulators was
     * invisible to 40062 test cases. */
    else if (strcmp(name, "st2") == 0) cpu->ST2 = value;
    else if (strcmp(name, "i1") == 0) cpu->I[0] = value;
    else if (strcmp(name, "i2") == 0) cpu->I[1] = value;
    else if (strcmp(name, "i3") == 0) cpu->I[2] = value;
    else if (strcmp(name, "i4") == 0) cpu->I[3] = value;
    else if (strcmp(name, "a1") == 0) cpu->A[0] = value;
    else if (strcmp(name, "a2") == 0) cpu->A[1] = value;
    else if (strcmp(name, "a3") == 0) cpu->A[2] = value;
    else if (strcmp(name, "a4") == 0) cpu->A[3] = value;
    else if (strcmp(name, "e1") == 0) cpu->E[0] = value;
    else if (strcmp(name, "e2") == 0) cpu->E[1] = value;
    else if (strcmp(name, "e3") == 0) cpu->E[2] = value;
    else if (strcmp(name, "e4") == 0) cpu->E[3] = value;
    else if (strcmp(name, "l") == 0) cpu->L = value;
    else if (strcmp(name, "b") == 0) cpu->B = value;
    else if (strcmp(name, "r") == 0) cpu->R = value;
    else if (strcmp(name, "p") == 0) cpu->L = value;  /* P = frame pointer = L */
    else if (strcmp(name, "tos") == 0) cpu->TOS = value;
    else if (strcmp(name, "ll") == 0) cpu->LL = value;
    else if (strcmp(name, "hl") == 0) cpu->HL = value;
    else if (strcmp(name, "tha") == 0) cpu->THA = value;
    else if (strcmp(name, "ced") == 0) cpu->CED = value;
    else if (strcmp(name, "cad") == 0) cpu->CAD = value;
    else if (strcmp(name, "ps") == 0) cpu->PS = value;
    else if (strcmp(name, "ote1") == 0) cpu->OTE1 = value;
    else if (strcmp(name, "ote2") == 0) cpu->OTE2 = value;
    else {
        /* FATAL: Unknown register - test data has register we don't support */
        fprintf(stderr, "FATAL ERROR: Unknown register '%s' in initial state!\n", name);
        fprintf(stderr, "This indicates the test generator is producing registers the C runner cannot handle.\n");
        fprintf(stderr, "Add support for '%s' in set_register() and get_register() functions.\n", name);
        exit(1);
    }
}

/**
 * Get a CPU register by name
 */
static uint32_t get_register(Nd500Cpu* cpu, const char* name) {
    if (strcmp(name, "pc") == 0) return cpu->PC;
    else if (strcmp(name, "st") == 0) return cpu->ST1;
    else if (strcmp(name, "st2") == 0) return cpu->ST2;   /* trap bits 32..41 */
    else if (strcmp(name, "i1") == 0) return cpu->I[0];
    else if (strcmp(name, "i2") == 0) return cpu->I[1];
    else if (strcmp(name, "i3") == 0) return cpu->I[2];
    else if (strcmp(name, "i4") == 0) return cpu->I[3];
    else if (strcmp(name, "a1") == 0) return cpu->A[0];
    else if (strcmp(name, "a2") == 0) return cpu->A[1];
    else if (strcmp(name, "a3") == 0) return cpu->A[2];
    else if (strcmp(name, "a4") == 0) return cpu->A[3];
    else if (strcmp(name, "e1") == 0) return cpu->E[0];
    else if (strcmp(name, "e2") == 0) return cpu->E[1];
    else if (strcmp(name, "e3") == 0) return cpu->E[2];
    else if (strcmp(name, "e4") == 0) return cpu->E[3];
    else if (strcmp(name, "l") == 0) return cpu->L;
    else if (strcmp(name, "b") == 0) return cpu->B;
    else if (strcmp(name, "r") == 0) return cpu->R;
    else if (strcmp(name, "p") == 0) return cpu->L;
    else if (strcmp(name, "tos") == 0) return cpu->TOS;
    else if (strcmp(name, "ll") == 0) return cpu->LL;
    else if (strcmp(name, "hl") == 0) return cpu->HL;
    else if (strcmp(name, "tha") == 0) return cpu->THA;
    else if (strcmp(name, "ced") == 0) return cpu->CED;
    else if (strcmp(name, "cad") == 0) return cpu->CAD;
    else if (strcmp(name, "ps") == 0) return cpu->PS;
    else if (strcmp(name, "ote1") == 0) return cpu->OTE1;
    else if (strcmp(name, "ote2") == 0) return cpu->OTE2;
    else {
        /* FATAL: Unknown register in expected state */
        fprintf(stderr, "FATAL ERROR: Unknown register '%s' in expected state!\n", name);
        fprintf(stderr, "This indicates the test generator is producing registers the C runner cannot validate.\n");
        fprintf(stderr, "Add support for '%s' in set_register() and get_register() functions.\n", name);
        exit(1);
    }
}

/**
 * Check if a register name is known/supported
 */
static int is_known_register(const char* name) {
    static const char* known_regs[] = {
        "pc", "st", "st2", "i1", "i2", "i3", "i4",
        "a1", "a2", "a3", "a4", "e1", "e2", "e3", "e4",
        "l", "b", "r", "p", "tos", "ll", "hl", "tha",
        "ced", "cad", "ps", "ote1", "ote2", NULL
    };
    for (int i = 0; known_regs[i] != NULL; i++) {
        if (strcmp(name, known_regs[i]) == 0) return 1;
    }
    return 0;
}

/**
 * Print detailed flag differences between actual and expected ST register.
 * This helps identify exactly which flag bit(s) are wrong.
 *
 * Flag bit positions in ST1 register:
 *   Bit 5 (0x20)  = Z (Zero)
 *   Bit 6 (0x40)  = C (Carry)
 *   Bit 7 (0x80)  = S (Sign)
 *   Bit 8 (0x100) = K (Key flag)
 *   Bit 9 (0x200) = O (Overflow)
 */
static void print_flag_differences(uint32_t expected, uint32_t actual) {
    uint32_t diff = expected ^ actual;

    /* Only check data status flag bits (5-9) */
    if ((diff & 0x3E0) == 0) {
        printf("    (No flag bit differences in Z/C/S/K/O)\n");
        return;
    }

    printf("    Flag differences:\n");

    if (diff & 0x20) {  /* Bit 5 = Z */
        printf("      Z (Zero):     expected=%d, actual=%d\n",
               (expected >> 5) & 1, (actual >> 5) & 1);
    }
    if (diff & 0x40) {  /* Bit 6 = C */
        printf("      C (Carry):    expected=%d, actual=%d\n",
               (expected >> 6) & 1, (actual >> 6) & 1);
    }
    if (diff & 0x80) {  /* Bit 7 = S */
        printf("      S (Sign):     expected=%d, actual=%d\n",
               (expected >> 7) & 1, (actual >> 7) & 1);
    }
    if (diff & 0x100) {  /* Bit 8 = K */
        printf("      K (Key):      expected=%d, actual=%d\n",
               (expected >> 8) & 1, (actual >> 8) & 1);
    }
    if (diff & 0x200) {  /* Bit 9 = O */
        printf("      O (Overflow): expected=%d, actual=%d\n",
               (expected >> 9) & 1, (actual >> 9) & 1);
    }

    /* Show both values in binary for debugging */
    printf("    Expected flags: Z=%d C=%d S=%d K=%d O=%d (0x%03X)\n",
           (expected >> 5) & 1, (expected >> 6) & 1, (expected >> 7) & 1,
           (expected >> 8) & 1, (expected >> 9) & 1, expected & 0x3FF);
    printf("    Actual flags:   Z=%d C=%d S=%d K=%d O=%d (0x%03X)\n",
           (actual >> 5) & 1, (actual >> 6) & 1, (actual >> 7) & 1,
           (actual >> 8) & 1, (actual >> 9) & 1, actual & 0x3FF);
}

/**
 * Validate CPU registers against expected values
 * Returns 0 on success, non-zero on failure
 * If print_details is true, prints mismatch details
 */
static int validate_registers(Nd500Cpu* cpu, cJSON* final_regs, int print_details) {
    int failures = 0;
    cJSON* reg;
    cJSON_ArrayForEach(reg, final_regs) {
        if (!cJSON_IsNumber(reg)) continue;

        const char* reg_name = reg->string;

        /* Check if register is known */
        if (!is_known_register(reg_name)) {
            if (print_details) {
                printf("  UNKNOWN register '%s' in expected final state!\n", reg_name);
            }
            unknown_reg_count++;
            failures++;  /* Treat unknown register as failure */
            continue;
        }

        uint32_t expected = (uint32_t)reg->valuedouble;
        uint32_t actual = get_register(cpu, reg_name);

        if (actual != expected) {
            if (print_details) {
                printf("  Register %s: expected 0x%08X (%u), got 0x%08X (%u)\n",
                       reg_name, expected, expected, actual, actual);

                /* For ST register, show granular flag differences */
                if (strcmp(reg_name, "st") == 0) {
                    print_flag_differences(expected, actual);
                }
                /* ST2 is the upper half of the same status word, so name the
                 * trap conditions rather than leaving a bare hex diff. These
                 * are the guard/interrupt-class traps; a mismatch here is
                 * almost always "the two CPUs disagree about which trap a
                 * malformed instruction raises". */
                else if (strcmp(reg_name, "st2") == 0) {
                    static const struct { uint32_t bit; const char* name; } st2_bits[] = {
                        { 1u << 0,  "XSE(32) index scaling error" },
                        { 1u << 1,  "IIC(33) illegal instruction code" },
                        { 1u << 2,  "IOS(34) illegal operand specifier" },
                        { 1u << 3,  "ISE(35) instruction sequence error" },
                        { 1u << 4,  "PV(36) protect violation" },
                        { 1u << 5,  "THM(37) trap handler missing" },
                        { 1u << 6,  "PGF(38) page fault" },
                        { 1u << 7,  "PWF(39) power failure" },
                        { 1u << 8,  "PRF(40) processor fault" },
                        { 1u << 9,  "HF(41) hardware fault" },
                    };
                    printf("    ST2 trap-condition differences:\n");
                    for (size_t i = 0; i < sizeof st2_bits / sizeof st2_bits[0]; i++) {
                        int e = (expected & st2_bits[i].bit) ? 1 : 0;
                        int a = (actual   & st2_bits[i].bit) ? 1 : 0;
                        if (e != a)
                            printf("      %-34s expected=%d, actual=%d\n",
                                   st2_bits[i].name, e, a);
                    }
                }
            }
            failures++;
        }
    }
    return failures;
}

/**
 * Validate memory against expected values
 * Returns 0 on success, non-zero on failure
 * If print_details is true, prints mismatch details
 * Note: Test generator uses two formats:
 *   - Byte values (0-255): compare single byte at address
 *   - Word values (>255): compare 32-bit big-endian word at address
 */
static int validate_memory(Nd500Machine* m, cJSON* final_ram, int print_details) {
    int failures = 0;
    cJSON* mem_entry;
    cJSON_ArrayForEach(mem_entry, final_ram) {
        if (!cJSON_IsArray(mem_entry) || cJSON_GetArraySize(mem_entry) < 2) continue;

        cJSON* addr_json = cJSON_GetArrayItem(mem_entry, 0);
        cJSON* val_json = cJSON_GetArrayItem(mem_entry, 1);

        if (!cJSON_IsNumber(addr_json) || !cJSON_IsNumber(val_json)) continue;

        uint32_t addr = (uint32_t)addr_json->valuedouble;
        uint32_t expected = (uint32_t)val_json->valuedouble;

        if (expected <= 255) {
            /* Byte comparison for small values */
            uint8_t actual = nd500_bus_read8(m, addr);
            if (actual != (uint8_t)expected) {
                if (print_details) {
                    printf("  Memory[0x%08X]: expected 0x%02X, got 0x%02X\n",
                           addr, (uint8_t)expected, actual);
                }
                failures++;
            }
        } else {
            /* 32-bit word comparison for large values (big-endian) */
            uint8_t b0 = nd500_bus_read8(m, addr + 0);
            uint8_t b1 = nd500_bus_read8(m, addr + 1);
            uint8_t b2 = nd500_bus_read8(m, addr + 2);
            uint8_t b3 = nd500_bus_read8(m, addr + 3);
            uint32_t actual = ((uint32_t)b0 << 24) | ((uint32_t)b1 << 16) |
                              ((uint32_t)b2 << 8) | (uint32_t)b3;

            if (actual != expected) {
                if (print_details) {
                    printf("  Memory[0x%08X]: expected 0x%08X, got 0x%08X\n",
                           addr, expected, actual);
                }
                failures++;
            }
        }
    }
    return failures;
}

/**
 * Validate ND-100 I/O processor memory against expected values.
 * Used for RIOM instruction testing to verify source memory is unchanged.
 *
 * Format: [[nd100_word_addr, halfword_value], ...]
 * Physical address: nd100_memory_offset + (nd100_addr * 2)
 */
static int validate_nd100_memory(Nd500Cpu* cpu, Nd500Machine* m, cJSON* final_nd100, int print_details) {
    int failures = 0;
    cJSON* mem_entry;
    cJSON_ArrayForEach(mem_entry, final_nd100) {
        if (!cJSON_IsArray(mem_entry) || cJSON_GetArraySize(mem_entry) < 2) continue;

        cJSON* addr_json = cJSON_GetArrayItem(mem_entry, 0);
        cJSON* val_json = cJSON_GetArrayItem(mem_entry, 1);

        if (!cJSON_IsNumber(addr_json) || !cJSON_IsNumber(val_json)) continue;

        uint32_t nd100_addr = (uint32_t)addr_json->valuedouble;
        uint16_t expected = (uint16_t)val_json->valuedouble;

        /* Calculate physical address: nd100_memory_offset + (nd100_addr * 2) */
        uint32_t phys_addr = cpu->nd100_memory_offset + (nd100_addr * 2);

        /* Read halfword (big-endian) */
        uint8_t hi = nd500_bus_read8(m, phys_addr);
        uint8_t lo = nd500_bus_read8(m, phys_addr + 1);
        uint16_t actual = ((uint16_t)hi << 8) | (uint16_t)lo;

        if (actual != expected) {
            if (print_details) {
                printf("  ND100[0x%06X] (phys 0x%08X): expected 0x%04X, got 0x%04X\n",
                       nd100_addr, phys_addr, expected, actual);
            }
            failures++;
        }
    }
    return failures;
}
