#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Minimal JSON scanner: extract opcode, mnemonic from instructions.json */
static void emit_header(FILE* out, const char* src_json) {
	fprintf(out, "/*\n");
	fprintf(out, " * AUTO-GENERATED FILE - DO NOT EDIT\n");
	fprintf(out, " * Generated by tools/gen_instructions from %s\n", src_json ? src_json : "instructions.json");
	fprintf(out, " */\n\n");
	fprintf(out, "#pragma once\n");
	fprintf(out, "#include <stdint.h>\n\n");
	fprintf(out, "typedef struct { uint16_t opcode; const char* mnemonic; uint8_t operands; } Nd500Instr;\n");
	fprintf(out, "extern const Nd500Instr g_nd500_instrs[];\n");
	fprintf(out, "extern const unsigned g_nd500_instrs_count;\n");
}

static void emit_source(FILE* out, const char** opcodes, const char** mnem, const char** ops, int count, const char* src_json) {
	fprintf(out, "/*\n");
	fprintf(out, " * AUTO-GENERATED FILE - DO NOT EDIT\n");
	fprintf(out, " * Generated by tools/gen_instructions from %s\n", src_json ? src_json : "instructions.json");
	fprintf(out, " */\n\n");
	fprintf(out, "#include \"nd500_instructions_gen.h\"\n\n");
	fprintf(out, "const Nd500Instr g_nd500_instrs[] = {\n");
	for (int i = 0; i < count; ++i) {
		const char* opc = opcodes[i] ? opcodes[i] : "0xFFFF";
		const char* mn = mnem[i] ? mnem[i] : "\"???\"";
		const char* oc = ops[i] ? ops[i] : "0";
		fprintf(out, "  { %s, %s, %s },\n", opc, mn, oc);
	}
	fprintf(out, "};\n");
	fprintf(out, "const unsigned g_nd500_instrs_count = %d;\n", count);
}

int main(int argc, char** argv) {
	if (argc < 4) {
		fprintf(stderr, "usage: gen_instructions <instructions.json> <out.h> <out.c>\n");
		return 1;
	}
	const char* in = argv[1];
	const char* out_h = argv[2];
	const char* out_c = argv[3];
	FILE* f = fopen(in, "rb");
	if (!f) { perror("open json"); return 1; }
	fseek(f, 0, SEEK_END);
	long sz = ftell(f);
	fseek(f, 0, SEEK_SET);
	char* buf = (char*)malloc((size_t)sz + 1);
	if (!buf) { fclose(f); return 1; }
	if (fread(buf, 1, (size_t)sz, f) != (size_t)sz) { fclose(f); free(buf); return 1; }
	buf[sz] = '\0';
	fclose(f);

	/* crude scanning */
	const int max = 600;
	const char* opcodes[max];
	const char* mnem[max];
	const char* ops[max];
	memset(opcodes, 0, sizeof(opcodes));
	memset(mnem, 0, sizeof(mnem));
	memset(ops, 0, sizeof(ops));
	int count = 0;
	char* p = buf;
    while ((p = strstr(p, "\"opcode\"")) && count < max) {
		char* colon = strchr(p, ':'); if (!colon) break;
		char* comma = strchr(colon, ','); if (!comma) break;
		*comma = '\0';
        static char opcbuf[32];
        const char* raw = colon+1;
        while (*raw==' '||*raw=='\t') raw++;
        if (*raw=='"') {
            raw++; const char* endq = strchr(raw, '"');
            if (!endq) { *comma = ','; break; }
            size_t n = (size_t)(endq - raw);
            if (n >= sizeof(opcbuf)) n = sizeof(opcbuf)-1;
            memcpy(opcbuf, raw, n); opcbuf[n] = '\0';
        } else {
            snprintf(opcbuf, sizeof(opcbuf), "%s", raw);
        }
        opcodes[count] = strdup(opcbuf); /* numeric like 0xFC04 */
		*comma = ',';
		char* m = strstr(comma, "\"mnemonic\""); if (!m) break;
		char* mcolon = strchr(m, ':'); if (!mcolon) break;
		char* mstart = strchr(mcolon, '"'); if (!mstart) break;
		char* mend = strchr(mstart+1, '"'); if (!mend) break;
		*mend = '\0';
        static char mnbuf[64];
        snprintf(mnbuf, sizeof(mnbuf), "\"%s\"", mstart+1);
		mnem[count] = strdup(mnbuf);
		*mend = '"';
		char* oc = strstr(mend+1, "\"operandCount\""); if (!oc) break;
		char* occ = strchr(oc, ':'); if (!occ) break;
		char* occe = strchr(occ, ','); if (!occe) occe = strchr(occ, '}');
		if (!occe) break;
		*occe = '\0';
		static char opcb[8];
		snprintf(opcb, sizeof(opcb), "%s", occ+1);
		ops[count] = strdup(opcb);
		*occe = ',';
		count++;
		p = occe;
	}

	FILE* oh = fopen(out_h, "wb"); if (!oh) return 1;
	emit_header(oh, in);
	fclose(oh);
	FILE* oc = fopen(out_c, "wb"); if (!oc) return 1;
	emit_source(oc, opcodes, mnem, ops, count, in);
	fclose(oc);
	return 0;
}


