#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Minimal JSON scanner: extract opcode, mnemonic from instructions.json */
static void emit_header(FILE* out, const char* src_json) {
	fprintf(out, "/*\n");
	fprintf(out, " * AUTO-GENERATED FILE - DO NOT EDIT\n");
	fprintf(out, " * Generated by tools/gen_instructions from %s\n", src_json ? src_json : "instructions.json");
	fprintf(out, " */\n\n");
	fprintf(out, "#pragma once\n");
	fprintf(out, "#include <stdint.h>\n\n");
    fprintf(out, "typedef struct { uint16_t opcode; const char* mnemonic; uint8_t operands; uint8_t prefixes_mask; uint8_t variant; uint32_t op_templates[4]; } Nd500Instr;\n");
	fprintf(out, "extern const Nd500Instr g_nd500_instrs[];\n");
	fprintf(out, "extern const unsigned g_nd500_instrs_count;\n");
}

static void emit_source(FILE* out, const char** opcodes, const char** mnem, const char** ops, const char** prefm, const char** variants, const char** templates, int count, const char* src_json) {
	fprintf(out, "/*\n");
	fprintf(out, " * AUTO-GENERATED FILE - DO NOT EDIT\n");
	fprintf(out, " * Generated by tools/gen_instructions from %s\n", src_json ? src_json : "instructions.json");
	fprintf(out, " */\n\n");
	fprintf(out, "#include \"nd500_instructions_gen.h\"\n\n");
	fprintf(out, "const Nd500Instr g_nd500_instrs[] = {\n");
	int total_count = 0;
	for (int i = 0; i < count; ++i) {
		const char* opc_str = opcodes[i] ? opcodes[i] : "0xFFFF";
		const char* mn = mnem[i] ? mnem[i] : "\"???\"";
        const char* oc = ops[i] ? ops[i] : "0";
        const char* pm_str = prefm[i] ? prefm[i] : "0";
        const char* vn_str = variants[i] ? variants[i] : "0";
        const char* tmpl_str = templates[i] ? templates[i] : "";
        
        /* Parse opcode, prefix mask, and variant */
        uint16_t base_opcode = (uint16_t)strtol(opc_str, NULL, 0);
        uint8_t mask = (uint8_t)strtol(pm_str, NULL, 0);
        uint8_t variant_num = (uint8_t)atoi(vn_str);
        
        /* Debug: show parsing for first few */
        if (i < 10) {
            fprintf(stderr, "[GEN] i=%d Opcode=%s, mask_str='%s', mask_parsed=0x%02X, R_N=%s\n", 
                    i, opc_str, pm_str ? pm_str : "NULL", mask, (mask & 0x40) ? "YES" : "NO");
        }
        
        /* Check if instruction has R_N (register variants) - bit 0x40 */
        int has_reg_variants = (mask & 0x40) ? 1 : 0;
        int reg_count = has_reg_variants ? 4 : 1;
        
        /* Parse operandTemplates - extract up to 4 hex values */
        uint32_t tmpl[4] = {0, 0, 0, 0};
        if (tmpl_str && *tmpl_str) {
            char* t = (char*)tmpl_str;
            for (int ti = 0; ti < 4; ti++) {
                while (*t && (*t == ' ' || *t == '\t' || *t == ',' || *t == '"')) t++;
                if (*t == '0' && (t[1] == 'x' || t[1] == 'X')) {
                    tmpl[ti] = (uint32_t)strtoul(t, &t, 0);
                } else break;
            }
        }
        
        /* Generate entry for each register variant (R1, R2, R3, R4) */
        for (int r = 0; r < reg_count; r++) {
            uint16_t actual_opcode = base_opcode + r;
            fprintf(out, "  { 0x%04X, %s, %s, 0x%02X, %d, {0x%08X, 0x%08X, 0x%08X, 0x%08X} },\n", 
                    actual_opcode, mn, oc, mask, variant_num, tmpl[0], tmpl[1], tmpl[2], tmpl[3]);
            total_count++;
        }
	}
	fprintf(out, "};\n");
	fprintf(out, "const unsigned g_nd500_instrs_count = %d;\n", total_count);
}

int main(int argc, char** argv) {
	if (argc < 4) {
		fprintf(stderr, "usage: gen_instructions <instructions.json> <out.h> <out.c>\n");
		return 1;
	}
	const char* in = argv[1];
	const char* out_h = argv[2];
	const char* out_c = argv[3];
	FILE* f = fopen(in, "rb");
	if (!f) { perror("open json"); return 1; }
	fseek(f, 0, SEEK_END);
	long sz = ftell(f);
	fseek(f, 0, SEEK_SET);
	char* buf = (char*)malloc((size_t)sz + 1);
	if (!buf) { fclose(f); return 1; }
	if (fread(buf, 1, (size_t)sz, f) != (size_t)sz) { fclose(f); free(buf); return 1; }
	buf[sz] = '\0';
	fclose(f);

	/* crude scanning */
	const int max = 1200;
	const char* opcodes[max];
	const char* mnem[max];
    const char* ops[max];
    const char* prefm[max];
    const char* variants[max];
    const char* templates[max];
	memset(opcodes, 0, sizeof(opcodes));
	memset(mnem, 0, sizeof(mnem));
    memset(ops, 0, sizeof(ops));
    memset(prefm, 0, sizeof(prefm));
    memset(variants, 0, sizeof(variants));
    memset(templates, 0, sizeof(templates));
	int count = 0;
	char* p = buf;
    while ((p = strstr(p, "\"opcode\"")) && count < max) {
		char* colon = strchr(p, ':'); if (!colon) break;
		char* comma = strchr(colon, ','); if (!comma) break;
		*comma = '\0';
        char opcbuf[32];
        const char* raw = colon+1;
        while (*raw==' '||*raw=='\t') raw++;
        if (*raw=='"') {
            raw++; const char* endq = strchr(raw, '"');
            if (!endq) { *comma = ','; break; }
            size_t n = (size_t)(endq - raw);
            if (n >= sizeof(opcbuf)) n = sizeof(opcbuf)-1;
            memcpy(opcbuf, raw, n); opcbuf[n] = '\0';
        } else {
            snprintf(opcbuf, sizeof(opcbuf), "%s", raw);
        }
        opcodes[count] = strdup(opcbuf); /* numeric like 0xFC04 */
		*comma = ',';
		char* m = strstr(comma, "\"mnemonic\""); if (!m) break;
		char* mcolon = strchr(m, ':'); if (!mcolon) break;
		char* mstart = strchr(mcolon, '"'); if (!mstart) break;
		char* mend = strchr(mstart+1, '"'); if (!mend) break;
		*mend = '\0';
        char mnbuf[64];
        snprintf(mnbuf, sizeof(mnbuf), "\"%s\"", mstart+1);
		mnem[count] = strdup(mnbuf);
		*mend = '"';
        
        /* prefixMask appears BEFORE operandCount in JSON - search from mend */
        char* next_instr = strstr(mend+1, "\"opcode\"");
        char* pmk = strstr(mend+1, "\"prefixMask\"");
        if (next_instr && pmk && pmk > next_instr) pmk = NULL; /* Don't cross into next instruction */
        
        char* oc = strstr(mend+1, "\"operandCount\""); if (!oc) break;
		char* occ = strchr(oc, ':'); if (!occ) break;
		char* occe = strchr(occ, ','); if (!occe) occe = strchr(occ, '}');
		if (!occe) break;
		*occe = '\0';
		char opcb[8];
		snprintf(opcb, sizeof(opcb), "%s", occ+1);
		ops[count] = strdup(opcb);
		*occe = ',';
        if (pmk) {
            char* pmc = strchr(pmk, ':');
            if (pmc) {
                char* pmce = strchr(pmc, ','); if (!pmce) pmce = strchr(pmc, '}');
                if (pmce) {
                    *pmce = '\0';
                    char pmb[16];
                    const char* rawpm = pmc+1; while (*rawpm==' '||*rawpm=='\t') rawpm++;
                    if (*rawpm=='"') {
                        rawpm++; const char* endq = strchr(rawpm, '"');
                        if (endq) {
                            size_t n = (size_t)(endq - rawpm);
                            if (n >= sizeof(pmb)) n = sizeof(pmb)-1;
                            memcpy(pmb, rawpm, n); pmb[n] = '\0';
                        } else {
                            snprintf(pmb, sizeof(pmb), "%s", rawpm);
                        }
                    } else {
                        snprintf(pmb, sizeof(pmb), "%s", rawpm);
                    }
                    prefm[count] = strdup(pmb);
                    *pmce = ',';
                }
            }
        }
        /* variantNumber */
        char* vnk = strstr(mend+1, "\"variantNumber\"");
        if (next_instr && vnk && vnk > next_instr) vnk = NULL;
        if (vnk) {
            char* vnc = strchr(vnk, ':');
            if (vnc) {
                char* vnce = strchr(vnc, ','); if (!vnce) vnce = strchr(vnc, '}');
                if (vnce) {
                    *vnce = '\0';
                    char vnb[8];
                    snprintf(vnb, sizeof(vnb), "%s", vnc+1);
                    variants[count] = strdup(vnb);
                    *vnce = ',';
                }
            }
        }
        /* operandTemplates - parse as comma-separated hex values in array */
        char* otk = strstr(mend+1, "\"operandTemplates\"");
        if (next_instr && otk && otk > next_instr) otk = NULL;
        if (otk) {
            char* bracket = strchr(otk, '[');
            if (bracket) {
                char* close_bracket = strchr(bracket, ']');
                if (close_bracket) {
                    *close_bracket = '\0';
                    char tmpbuf[256];
                    snprintf(tmpbuf, sizeof(tmpbuf), "%s", bracket+1);
                    templates[count] = strdup(tmpbuf);
                    *close_bracket = ']';
                }
            }
        }
		count++;
		p = occe;
	}

	FILE* oh = fopen(out_h, "wb"); if (!oh) return 1;
	emit_header(oh, in);
	fclose(oh);
	FILE* oc = fopen(out_c, "wb"); if (!oc) return 1;
    emit_source(oc, opcodes, mnem, ops, prefm, variants, templates, count, in);
	fclose(oc);
	return 0;
}


