/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by tools/gen_instructions from src/cpu/instructions.json
 */

#pragma once
#include <stdint.h>

/* has_variable_operands was missing here while src/cpu/instructions_gen.c has
 * always emitted a value for it. Six scalars into a five-scalar struct meant
 * that value landed in op_templates[0], the brace group went to
 * op_templates[1], and its last three entries were discarded as excess - so
 * every row came out as {0, <first template>, 0, 0} instead of the four real
 * templates. Both files are currently OUT of the build (the live table is
 * src/cpu/nd500_instructions.c, whose own header does declare the field), so
 * nothing was decoding wrongly, but anything that compiled this pair got
 * silently wrong operand templates rather than an error. */
typedef struct { uint16_t opcode; const char* mnemonic; uint8_t operands; uint8_t prefixes_mask; uint8_t variant; uint8_t has_variable_operands; uint32_t op_templates[4]; } Nd500Instr;
extern const Nd500Instr g_nd500_instrs[];
extern const unsigned g_nd500_instrs_count;
