#!/usr/bin/env python3
"""gen_float_exact_vectors.py - write test/float_exact_vectors.h.

SPDX-License-Identifier: MIT
Copyright (c) 2025-2026 Ronny Hansen

ND-500 float add/sub/mul/div vectors for test/test_float_exact.c.

The expected results come from exact rational arithmetic (fractions.Fraction),
rounded by ND-05.009.4 7.2.7 (add one to the mantissa if G=1 and (St=1 or L=1)),
with the floating overflow and underflow results of 6.5.1. This is independent of
src/cpu/float_exact.c, which works on integer significands.

Usage: tools/gen_float_exact_vectors.py > test/float_exact_vectors.h
"""
import random
from fractions import Fraction as Fr

FO, FU, DZ = 1, 2, 4


def decode(b, mb):
    s = (b >> (mb + 9)) & 1
    e = (b >> mb) & 511
    if e == 0:
        return Fr(0)
    v = Fr((1 << mb) | (b & ((1 << mb) - 1)), 1 << (mb + 1)) * Fr(2) ** (e - 256)
    return -v if s else v


def encode(v, mb):
    if v == 0:
        return 0, 0
    neg = v < 0
    v = abs(v)
    sign = (1 << (mb + 9)) if neg else 0
    e = v.numerator.bit_length() - v.denominator.bit_length()
    while v / Fr(2) ** e >= 1:
        e += 1
    while v / Fr(2) ** e < Fr(1, 2):
        e -= 1
    m = v / Fr(2) ** e * (1 << (mb + 1))
    q = m.numerator // m.denominator
    rem = m - q
    g = rem >= Fr(1, 2)
    st = rem != 0 and rem != Fr(1, 2)
    if g and (st or q & 1):
        q += 1
    if q >> (mb + 1):
        q >>= 1
        e += 1
    exp = e + 256
    if exp > 511:
        return sign | (511 << mb) | ((1 << mb) - 1), FO
    if exp < 1:
        return sign, FU
    return sign | (exp << mb) | (q & ((1 << mb) - 1)), 0


def operand(rng, mb):
    r = rng.random()
    if r < 0.04:
        return 0
    e = rng.choice([rng.randint(1, 511), rng.randint(240, 272), rng.randint(254, 258)])
    b = (rng.getrandbits(1) << (mb + 9)) | (e << mb) | rng.getrandbits(mb)
    if rng.random() < 0.2:
        b &= ~((1 << rng.randint(0, mb)) - 1)
    return b


def main():
    rng = random.Random(500)
    rows = []
    for dbl in (0, 1):
        mb = 54 if dbl else 22
        for _ in range(60):
            a = operand(rng, mb)
            b = operand(rng, mb)
            if rng.random() < 0.3:
                b = (b & ~(511 << mb)) | (((a >> mb) & 511) << mb)
            for op in "+-*/":
                x, y = decode(a, mb), decode(b, mb)
                if op == "/" and y == 0:
                    rows.append((dbl, op, a, b, a, DZ))
                    continue
                v = {"+": x + y, "-": x - y, "*": x * y, "/": x / y if y else 0}[op]
                r, exc = encode(v, mb)
                rows.append((dbl, op, a, b, r, exc))
    print("/* float_exact_vectors.h - generated by tools/gen_float_exact_vectors.py; do not edit. */")
    print("/* is_double, op, a, b, expected result, expected exceptions (1 FO, 2 FU, 4 DZ) */")
    print("static const struct { int is_double; char op; uint64_t a, b, r; unsigned exc; } k_vectors[] = {")
    for dbl, op, a, b, r, exc in rows:
        print("    { %d, '%s', 0x%016XULL, 0x%016XULL, 0x%016XULL, %d }," % (dbl, op, a, b, r, exc))
    print("};")


if __name__ == "__main__":
    main()
